### PR TITLE
Add new step to implemente BDD with Selenium and Flask-Testing

### PR DESCRIPTION
**Pull request by CharlyJazz**
Learn how test the login flow, fill the inputs and expected a flash message :bulb:

### CODE REVIEW

**Comment by CharlyJazz** [comment]
@mjhea0  Ready to merge?

**Comment by CharlyJazz** [comment]
Sure let me work in that

**Comment by CharlyJazz** [comment]
Ca u help me with this? I dont have time

**Comment by mjhea0** [comment]
@CharlyJazz I won't have time for a while either

**Pull request closed without merging**
